name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install latest shellcheck
      run: brew install shellcheck

    - name: Lint shell scripts
      run: shellcheck -P SCRIPTDIR **/*.sh
