name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install tools
      run: apt install -y shellcheck fish

    - name: Lint shell scripts
      run: shellcheck -P SCRIPTDIR *.sh **/*.sh

    - name: Check syntax of fish scripts
      run: |
          for file in *.fish **/*.fish; do
            if [ -f $file ]; then
              fish --no-execute $file
            fi
          done
