name: Test Brewfiles

on:
  push:
    paths:
      - 'package/brew/**'
      - '.github/workflows/test-brew.yml'
  pull_request:
    paths:
      - 'package/brew/**'
      - '.github/workflows/test-brew.yml'
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * 6'

jobs:
  test:
    name: Test Brewfiles
    defaults:
      run:
        working-directory: package/brew

    runs-on: macos-latest
    
    env:
      HOMEBREW_BUNDLE_BREW_SKIP: awscli

    steps:
      - uses: actions/checkout@v2
        
      - run: 'echo skipped: $HOMEBREW_BUNDLE_BREW_SKIP'

      - run: brew update

      - name: install from Brewfiles and check
        run: |
          for file in *.rb; do
            echo Install from $file &&
            brew bundle install --file $file --no-lock &&
            brew bundle check --file $file
          done
