name: Test Brewfiles

on:
  push:
    paths:
      - 'package/brew/**'
      - '.github/workflows/test-brew.yml'
  pull_request:
    paths:
      - 'package/brew/**'
      - '.github/workflows/test-brew.yml'
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * 6'

jobs:
  test:
    name: Test Brewfiles
    defaults:
      run:
        working-directory: package/brew

    runs-on: macos-latest
    
    env:
      HOMEBREW_BUNDLE_BREW_SKIP: awscli go

    steps:
      - uses: actions/checkout@v2
        
      - run: 'echo skipped: $HOMEBREW_BUNDLE_BREW_SKIP'

      - run: brew update

      - name: install from Brewfile and check
        run: |
          mas="$(brew bundle list --mas --file Brewfile.rb | tr '\n' ',')"
          HOMEBREW_BUNDLE_MAS_SKIP="$mas" brew bundle install --file Brewfile.rb --no-lock &&
          HOMEBREW_BUNDLE_MAS_SKIP="$mas" brew bundle check --file Brewfile.rb
